name: Linting and formatting

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    name: Linting with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff linting
        run: ruff .

      - name: Run Black formatting check
        run: black . --check
