# Generated by Django 4.0.3 on 2022-04-18 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Gear_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country_state', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('water', models.CharField(choices=[('Salt', 'salt'), ('Fresh', 'fresh')], max_length=6)),
                ('depth', models.IntegerField()),
                ('time', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start_pressure', models.IntegerField(blank=True, null=True)),
                ('end_pressure', models.IntegerField(blank=True, null=True)),
                ('tank_vol', models.FloatField(blank=True, default=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(choices=[('Metric', 'metric'), ('Imperial', 'imperial')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gear_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_serviced', models.DateField(blank=True, null=True)),
                ('custom_gear_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surfaceintervalapi.custom_gear_type')),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.diver')),
            ],
        ),
        migrations.CreateModel(
            name='Gear_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.dive')),
            ],
        ),
        migrations.CreateModel(
            name='Gear_Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.IntegerField()),
                ('bcd', models.ForeignKey(limit_choices_to={'gear_type__name': 'BCD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BCD', to='surfaceintervalapi.gear_item')),
                ('boots', models.ForeignKey(limit_choices_to={'gear_type__name': 'Boots'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Boots', to='surfaceintervalapi.gear_item')),
                ('computer', models.ForeignKey(limit_choices_to={'gear_type__name': 'Computer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Computer', to='surfaceintervalapi.gear_item')),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.diver')),
                ('exposure_suit', models.ForeignKey(limit_choices_to={'gear_type__name': 'Exposure Suit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exposure_Suit', to='surfaceintervalapi.gear_item')),
                ('fins', models.ForeignKey(limit_choices_to={'gear_type__name': 'Fins'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Fins', to='surfaceintervalapi.gear_item')),
                ('mask', models.ForeignKey(limit_choices_to={'gear_type__name': 'Mask'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mask', to='surfaceintervalapi.gear_item')),
                ('octopus', models.ForeignKey(limit_choices_to={'gear_type__name': 'Octopus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Octopus', to='surfaceintervalapi.gear_item')),
                ('regulator', models.ForeignKey(limit_choices_to={'gear_type__name': 'Regulator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Regulator', to='surfaceintervalapi.gear_item')),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surfaceintervalapi.gear_item')),
            ],
        ),
        migrations.AddField(
            model_name='gear_item',
            name='gear_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surfaceintervalapi.gear_type'),
        ),
        migrations.CreateModel(
            name='Favorite_Dive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.dive')),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.diver')),
            ],
        ),
        migrations.AddField(
            model_name='diver',
            name='default_Gear_Set',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Gear_Set', to='surfaceintervalapi.gear_set'),
        ),
        migrations.AddField(
            model_name='diver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Dive_Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.dive')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.specialty')),
            ],
        ),
        migrations.AddField(
            model_name='dive',
            name='Gear_Set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surfaceintervalapi.gear_set'),
        ),
        migrations.AddField(
            model_name='dive',
            name='diver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.diver'),
        ),
        migrations.CreateModel(
            name='Custom_Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.diver')),
            ],
        ),
        migrations.AddField(
            model_name='custom_gear_type',
            name='diver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.diver'),
        ),
        migrations.CreateModel(
            name='Certification_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('image_front_url', models.URLField()),
                ('image_back_url', models.URLField()),
                ('diver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.diver')),
            ],
        ),
    ]
