# Generated by Django 4.2.6 on 2023-10-22 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomGearType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CustomSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Dive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("country_state", models.CharField(max_length=255)),
                ("site", models.CharField(max_length=255)),
                (
                    "water",
                    models.CharField(choices=[("Salt", "salt"), ("Fresh", "fresh")], max_length=6),
                ),
                ("depth", models.IntegerField()),
                ("time", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("start_pressure", models.IntegerField(blank=True, null=True)),
                ("end_pressure", models.IntegerField(blank=True, null=True)),
                ("tank_vol", models.FloatField(blank=True, default=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Diver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        choices=[("Metric", "metric"), ("Imperial", "imperial")], max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GearItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("last_serviced", models.DateField(blank=True, null=True)),
                (
                    "custom_gear_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surfaceintervalapi.customgeartype",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.diver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GearType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField()),
                (
                    "dive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.dive"
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.diver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GearSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="GearSet", max_length=50)),
                ("weights", models.IntegerField(blank=True, null=True)),
                (
                    "bcd",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "BCD"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="BCD",
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
                (
                    "boots",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "Boots"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Boots",
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
                (
                    "computer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "Computer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Computer",
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.diver"
                    ),
                ),
                (
                    "exposure_suit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "Exposure suit"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Exposure_Suit",
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
                (
                    "fins",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "Fins"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Fins",
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
                (
                    "mask",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "Mask"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Mask",
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
                (
                    "octopus",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "Octopus"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Octopus",
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
                (
                    "regulator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "Regulator"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Regulator",
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"gear_type__name": "Tank"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gearitem",
            name="gear_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="surfaceintervalapi.geartype",
            ),
        ),
        migrations.CreateModel(
            name="FavoriteDive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dive",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.dive"
                    ),
                ),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.diver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiveSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "custom_specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surfaceintervalapi.customspecialty",
                    ),
                ),
                (
                    "dive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.dive"
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surfaceintervalapi.specialty",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="diver",
            name="default_gear_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="GearSet",
                to="surfaceintervalapi.gearset",
            ),
        ),
        migrations.AddField(
            model_name="diver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="diver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.diver"
            ),
        ),
        migrations.AddField(
            model_name="dive",
            name="gear_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="surfaceintervalapi.gearset"
            ),
        ),
        migrations.AddField(
            model_name="customspecialty",
            name="diver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.diver"
            ),
        ),
        migrations.AddField(
            model_name="customgeartype",
            name="diver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.diver"
            ),
        ),
        migrations.CreateModel(
            name="CertificationCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_issued", models.DateField()),
                ("image_front_url", models.URLField()),
                ("image_back_url", models.URLField()),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surfaceintervalapi.diver"
                    ),
                ),
            ],
        ),
    ]
