# Generated by Django 4.2.6 on 2023-11-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("surfaceintervalapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dive",
            name="gear_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="surfaceintervalapi.gearset",
            ),
        ),
    ]
