# Generated by Django 4.0.3 on 2022-04-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfaceintervalapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diver',
            name='default_Gear_Set',
        ),
        migrations.AddField(
            model_name='diver',
            name='default_gear_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Gear_Set', to='surfaceintervalapi.gear_set'),
        ),
    ]
