# Generated by Django 4.2.6 on 2023-11-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surfaceintervalapi", "0003_rename_country_state_dive_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
