# Generated by Django 4.0.3 on 2022-04-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfaceintervalapi', '0003_rename_gear_set_dive_gear_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear_set',
            name='bcd',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'BCD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BCD', to='surfaceintervalapi.gear_item'),
        ),
        migrations.AlterField(
            model_name='gear_set',
            name='boots',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'Boots'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Boots', to='surfaceintervalapi.gear_item'),
        ),
        migrations.AlterField(
            model_name='gear_set',
            name='computer',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'Computer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Computer', to='surfaceintervalapi.gear_item'),
        ),
        migrations.AlterField(
            model_name='gear_set',
            name='exposure_suit',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'Exposure Suit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exposure_Suit', to='surfaceintervalapi.gear_item'),
        ),
        migrations.AlterField(
            model_name='gear_set',
            name='fins',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'Fins'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Fins', to='surfaceintervalapi.gear_item'),
        ),
        migrations.AlterField(
            model_name='gear_set',
            name='mask',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'Mask'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mask', to='surfaceintervalapi.gear_item'),
        ),
        migrations.AlterField(
            model_name='gear_set',
            name='octopus',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'Octopus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Octopus', to='surfaceintervalapi.gear_item'),
        ),
        migrations.AlterField(
            model_name='gear_set',
            name='regulator',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'Regulator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Regulator', to='surfaceintervalapi.gear_item'),
        ),
        migrations.AlterField(
            model_name='gear_set',
            name='weights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
