# Generated by Django 4.2.6 on 2023-11-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("surfaceintervalapi", "0004_alter_specialty_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gearitem",
            name="last_serviced",
        ),
        migrations.RemoveField(
            model_name="gearitem",
            name="purchase_date",
        ),
        migrations.AlterField(
            model_name="gearitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gearset",
            name="tank",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"gear_type__name": "Tank"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Tank",
                to="surfaceintervalapi.gearitem",
            ),
        ),
        migrations.CreateModel(
            name="GearItemServiceInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("dives", models.IntegerField()),
                ("days", models.IntegerField()),
                (
                    "gear_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GearItemService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("service_date", models.DateField()),
                (
                    "gear_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
            ],
        ),
    ]
