# Generated by Django 4.0.3 on 2022-04-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfaceintervalapi', '0004_alter_gear_set_bcd_alter_gear_set_boots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive_specialty',
            name='custom_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.custom_specialty'),
        ),
        migrations.AlterField(
            model_name='dive_specialty',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.specialty'),
        ),
    ]
