# Generated by Django 4.2.6 on 2025-05-13 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("surfaceintervalapi", "0006_rename_weights_gearset_weight_remove_gearset_bcd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GearDive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surfaceintervalapi.dive",
                    ),
                ),
                (
                    "gear_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surfaceintervalapi.gearitem",
                    ),
                ),
            ],
        ),
    ]
