# Generated by Django 4.0.3 on 2022-04-19 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfaceintervalapi', '0006_certification_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_dive',
            name='dive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.dive', unique=True),
        ),
    ]
