# Generated by Django 4.2.6 on 2025-05-14 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surfaceintervalapi", "0007_geardive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gearitemserviceinterval",
            old_name="days",
            new_name="day_interval",
        ),
        migrations.RenameField(
            model_name="gearitemserviceinterval",
            old_name="dives",
            new_name="dive_interval",
        ),
    ]
