# Generated by Django 4.0.3 on 2022-04-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfaceintervalapi', '0008_alter_favorite_dive_dive'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear_set',
            name='name',
            field=models.CharField(default='GearSet', max_length=50),
        ),
    ]
