# Generated by Django 4.0.3 on 2022-04-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfaceintervalapi', '0012_alter_gear_set_exposure_suit_alter_gear_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear_set',
            name='tank',
            field=models.ForeignKey(blank=True, limit_choices_to={'gear_type__name': 'Tank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surfaceintervalapi.gear_item'),
        ),
    ]
