# Generated by Django 4.0.3 on 2022-04-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfaceintervalapi', '0013_alter_gear_set_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='diver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surfaceintervalapi.diver'),
            preserve_default=False,
        ),
    ]
