# Generated by Django 4.0.3 on 2022-04-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfaceintervalapi', '0014_images_diver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
