name: Linting, formatting, and testing

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff linting
        run: ruff .

      - name: Run Black formatting check
        run: black . --check

      - name: Running Unit Tests
        run: |
          python3 manage.py test
