import os
os.system('python3 manage.py loaddata users')
os.system('python3 manage.py loaddata tokens')
os.system('python3 manage.py loaddata divers')
os.system('python3 manage.py loaddata specialties')
os.system('python3 manage.py loaddata custom_specialties')
os.system('python3 manage.py loaddata gear_types')
os.system('python3 manage.py loaddata custom_gear_types')
os.system('python3 manage.py loaddata gear_items')
os.system('python3 manage.py loaddata gear_sets')
os.system('python3 manage.py loaddata dives')
os.system('python3 manage.py loaddata images')
os.system('python3 manage.py loaddata dive_specialties')
os.system('python3 manage.py loaddata certification_cards')
os.system('python3 manage.py loaddata favorite_dives')